Repository CapstoneDesign-2022/FindDict-Client, pull requests merged in 2022-11, with the labels that each got.

#33 [FEAT] 게임 로직 구현
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindDict/FindDict/Application/SceneDelegate.swift
  FindDict/FindDict/Global/Base/ModalBaseVC.swift
  FindDict/FindDict/Global/Extensions/UIColor+.swift
  FindDict/FindDict/Global/Extensions/UIView+.swift
  FindDict/FindDict/Resources/WordDictionary.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryCard.swift
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
  FindDict/FindDict/Sources/Scences/Game/ObjectDetection.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorVC.swift
  FindDict/FindDict/Sources/Scences/Game/TargetListComponentView.swift
  FindDict/FindDict/Sources/Scences/Main/MainVC.swift
Labels: 📱 UI

#32 [FEAT] 힌트 모달 뷰
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict/Resources/Assets.xcassets/closeImage.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/closeImage.imageset/x.png
  FindDict/FindDict/Resources/Assets.xcassets/globe.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/globe.imageset/globe.jpeg
  FindDict/FindDict/Sources/Scences/Game/HintModalVC.swift
Labels: 📱 UI

#35 [FEAT] 플로우 연결 시도#34
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict/Global/Base/ModalBaseVC.swift
  FindDict/FindDict/Global/Extensions/UIColor+.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryVC.swift
  FindDict/FindDict/Sources/Scences/Game/GameResultModal/GameResultSuccessVC.swift
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorVC.swift
Labels: 🐞 bug, help wanted

#38 [FEAT] 정답 시 모달 등장 및 소리 출력
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict/Global/Extensions/UIFont+.swift
  FindDict/FindDict/Sources/Components/SpeechButton.swift
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
  FindDict/FindDict/Sources/Scences/Game/GuessedRightWordVC.swift
  FindDict/FindDict/Sources/Scences/Game/TargetListComponentView.swift
Labels: 📱 UI, logic

#39 [FEAT] 게임방법 화면 뷰#28
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindDict/FindDict/Global/Extensions/UIViewController+.swift
  FindDict/FindDict/Protocols/Reusable.swift
  FindDict/FindDict/Resources/Assets.xcassets/Dictionary.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/Dictionary.imageset/Dictionary.png
  FindDict/FindDict/Resources/Assets.xcassets/DictionaryDetail.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/DictionaryDetail.imageset/DictionaryDetail.png
  FindDict/FindDict/Resources/Assets.xcassets/FoundAnswer.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/FoundAnswer.imageset/FoundAnswer.png
  FindDict/FindDict/Resources/Assets.xcassets/Game.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/Game.imageset/Game.png
  FindDict/FindDict/Resources/Assets.xcassets/GameOver.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/GameOver.imageset/GameOver.png
  FindDict/FindDict/Resources/Assets.xcassets/Hint.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/Hint.imageset/Hint.png
  FindDict/FindDict/Resources/Assets.xcassets/tutorialExampleImage.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/tutorialExampleImage.imageset/Screen Shot 2022-10-06 at 8.54.34 PM.png
  FindDict/FindDict/Sources/Scences/Main/mainVC.swift
  FindDict/FindDict/Sources/Scences/Tutorial/GameTutorialCVC.swift
  FindDict/FindDict/Sources/Scences/Tutorial/GameTutorialCVCModel.swift
  FindDict/FindDict/Sources/Scences/Tutorial/GameTutorialVC.swift
Labels: 📱 UI

#40 [FEAT] 단어장 상세보기 뷰
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindDict/FindDict/Model/WordListResponseModel.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryCard.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryDetailCVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryDetailVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryTVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryVC.swift
  FindDict/FindDict/Sources/Scences/Tutorial/GameTutorialVC.swift
Labels: 📱 UI

#51 [FEAT] 힌트 모달 연결 및 네트워크 통신 결과 반영
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindDict/FindDict/Global/Extensions/UIImage+.swift
  FindDict/FindDict/Global/Extensions/UIImageView+.swift
  FindDict/FindDict/Info.plist
  FindDict/FindDict/Model/HintResponseModel.swift
  FindDict/FindDict/Network/APIManagers/WordAPI.swift
  FindDict/FindDict/Network/Services/WordService.swift
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
  FindDict/FindDict/Sources/Scences/Game/HintModalVC.swift
  FindDict/FindDict/Sources/Scences/Game/TargetListComponentView.swift
Labels: 📱 UI, 📡 Network

#52 [FEAT] 단어 상세보기(사진) 네트워크 통신
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict/Global/Extensions/UIImage+.swift
  FindDict/FindDict/Global/Extensions/UIImageView+.swift
  FindDict/FindDict/Model/WordDetailResponseModel.swift
  FindDict/FindDict/Model/WordListResponseModel.swift
  FindDict/FindDict/Network/APIEssentials/NetworkConstants.swift
  FindDict/FindDict/Network/APIManagers/WordAPI.swift
  FindDict/FindDict/Network/Services/WordService.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryCard.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryDetailCVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryDetailVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryTVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryVC.swift
Labels: 📱 UI, 📡 Network

#54 [FIX] 단어 생성 API 네트워크 통신 에러 해결
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict/Model/CreateWordBodyModel.swift
  FindDict/FindDict/Model/CreateWordResponseModel.swift
  FindDict/FindDict/Network/APIManagers/WordAPI.swift
  FindDict/FindDict/Network/Services/WordService.swift
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
Labels: 🐞 bug, 📡 Network

#55 [FEAT] 로그인 성공/실패 alert창
  FindDict/FindDict.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindDict/FindDict/Global/MessageType.swift
  FindDict/FindDict/Sources/Scences/Auth/SignInVC.swift
  FindDict/FindDict/Sources/Scences/Auth/SignUpVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryVC.swift
  FindDict/FindDict/Sources/Scences/Main/mainVC.swift
Labels: 📱 UI

#57 [Docs] 생략된 타입 명시 및 MARK 구문 추가
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindDict/FindDict/Global/Base/AuthBaseVC.swift
  FindDict/FindDict/Global/Base/ModalBaseVC.swift
  FindDict/FindDict/Global/Extensions/CGRect+.swift
  FindDict/FindDict/Global/Extensions/TextField.swift
  FindDict/FindDict/Sources/Components/GameResultButton.swift
  FindDict/FindDict/Sources/Components/MainButton.swift
  FindDict/FindDict/Sources/Components/SpeechButton.swift
  FindDict/FindDict/Sources/Scences/Auth/BeforeSignInVC.swift
  FindDict/FindDict/Sources/Scences/Auth/SignInVC.swift
  FindDict/FindDict/Sources/Scences/Auth/SignUpVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryCard.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryDetailCVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryDetailVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryTVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryVC.swift
  FindDict/FindDict/Sources/Scences/Game/DrawingBoundingBoxView.swift
  FindDict/FindDict/Sources/Scences/Game/GameResultModal/GameResultFailVC.swift
  FindDict/FindDict/Sources/Scences/Game/GameResultModal/GameResultSuccessVC.swift
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
  FindDict/FindDict/Sources/Scences/Game/GuessedRightWordVC.swift
  FindDict/FindDict/Sources/Scences/Game/HintModalVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorButton.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorVC.swift
  FindDict/FindDict/Sources/Scences/Game/TargetListComponentView.swift
  FindDict/FindDict/Sources/Scences/Main/mainVC.swift
  FindDict/FindDict/Sources/Scences/Tutorial/GameTutorialCVC.swift
  FindDict/FindDict/Sources/Scences/Tutorial/GameTutorialVC.swift
Labels: 📄 documentation

#59 [CHORE] Accent Color 및 App Icon 설정
  FindDict/FindDict/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  FindDict/FindDict/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/icon.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/icon.imageset/icon.png
Labels: 🧺 chore

#61 [FEAT] launch screen 설정
  FindDict/FindDict/Application/AppDelegate.swift
  FindDict/FindDict/Resources/Assets.xcassets/launchScreen.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/launchScreen.imageset/launchScreen.png
  FindDict/FindDict/Sources/Scences/Base.lproj/LaunchScreen.storyboard
Labels: 📱 UI

#63 [FEAT] 단어 사진 확인하기 컬렉션 뷰 기본 이미지
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryDetailVC.swift
Labels: 📱 UI

#64 [FIX] UI 수정
  FindDict/FindDict/Sources/Scences/Auth/SignInVC.swift
  FindDict/FindDict/Sources/Scences/Auth/SignUpVC.swift
  FindDict/FindDict/Sources/Scences/Game/HintModalVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorVC.swift
  FindDict/FindDict/Sources/Scences/Main/mainVC.swift
Labels: 🐞 bug, 📱 UI

#69 Feat: 인식된 물체가 3개 이하일 때 사진 다시 선택
  FindDict/FindDict/Resources/Assets.xcassets/alertImage.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/alertImage.imageset/image 26.png
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoReSelectVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorVC.swift
Labels: 📱 UI

#70 [FEAT] 객체 인식 코드와 게임 진행 코드 파일 분리 외
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict/Application/SceneDelegate.swift
  FindDict/FindDict/Global/Extensions/UIImageView+.swift
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
  FindDict/FindDict/Sources/Scences/Game/ObjectDetector.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoReselectModalVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorVC.swift
Labels: 🐞 bug, ✨refactor, 📱 UI, logic

#72 [FEAT] 게임 초기화 구현
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict/Global/Extensions/UIStackView+.swift
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
Labels: 🐞 bug, 📱 UI, logic
