Repository CapstoneDesign-2022/FindDict-Client, pull requests merged in 2022-12, with the labels that each got.

#76 [REFACTOR] MainVC, BeforeSignInVC 수정
  FindDict/FindDict/Global/Extensions/UIFont+.swift
  FindDict/FindDict/Sources/Components/MainButton.swift
  FindDict/FindDict/Sources/Scences/Auth/BeforeSignInVC.swift
  FindDict/FindDict/Sources/Scences/Main/mainVC.swift
Labels: ✨refactor, 📱 UI

#74 [CHORE] 네트워크 세팅 수정
  FindDict/FindDict/Network/APIEssentials/APIConstants.swift
  FindDict/FindDict/Network/APIEssentials/NetworkConstants.swift
Labels: 🧺 chore

#81 [Feat] 타겟 버튼 단어 한글에서 영어로 변경
  FindDict/FindDict/Sources/Scences/Game/TargetListComponentView.swift
Labels: logic

#83 [Feat] 그림자 적용
  FindDict/FindDict/Global/Base/ModalBaseVC.swift
  FindDict/FindDict/Sources/Components/GameResultButton.swift
  FindDict/FindDict/Sources/Components/MainButton.swift
  FindDict/FindDict/Sources/Components/SpeechButton.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryCard.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryDetailVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryVC.swift
  FindDict/FindDict/Sources/Scences/Game/HintModalVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoReselectModalVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorButton.swift
  FindDict/FindDict/Sources/Scences/Game/TargetListComponentView.swift
Labels: 📱 UI

#78 [Feat] 찾을 물체 순서 부여
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
  FindDict/FindDict/Sources/Scences/Game/TargetListComponentView.swift
Labels: logic

#87 [Chore] 기본 이미지 넣기, 맞췄을 때 나오는 이미지 수정
  FindDict/FindDict/Resources/Assets.xcassets/CorrectSignImage.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/CorrectSignImage.imageset/CorrectSignImage 2.png
  FindDict/FindDict/Resources/Assets.xcassets/CorrectSignImage.imageset/CorrectSignImage 2@2x.png
  FindDict/FindDict/Resources/Assets.xcassets/CorrectSignImage.imageset/CorrectSignImage 2@3x.png
  FindDict/FindDict/Resources/Assets.xcassets/defaultGameImage.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/defaultGameImage.imageset/defaultImage 1.png
  FindDict/FindDict/Resources/Assets.xcassets/defaultGameImage.imageset/defaultImage 1@2x.png
  FindDict/FindDict/Resources/Assets.xcassets/defaultGameImage.imageset/defaultImage 1@3x.png
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorVC.swift
Labels: 🧺 chore

#85 [FEAT] 커스텀 네비바 제작 및 적용
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict/Global/Extensions/UIFont+.swift
  FindDict/FindDict/Resources/Assets.xcassets/home.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/home.imageset/home.svg
  FindDict/FindDict/Resources/Assets.xcassets/left_arrow.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/left_arrow.imageset/left_arrow.svg
  FindDict/FindDict/Sources/Components/DefaultNavigationBar.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryVC.swift
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorVC.swift
  FindDict/FindDict/Sources/Scences/Tutorial/GameTutorialVC.swift
Labels: 📱 UI

#90 [FEAT] 게임 오답 처리, 사진 선택 뷰 & 튜토리얼 뷰 디자인 수정
  FindDict/FindDict/Global/Base/ModalBaseVC.swift
  FindDict/FindDict/Global/Extensions/UIFont+.swift
  FindDict/FindDict/Sources/Components/MainButton.swift
  FindDict/FindDict/Sources/Components/SpeechButton.swift
  FindDict/FindDict/Sources/Scences/Auth/SignUpVC.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryCard.swift
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
  FindDict/FindDict/Sources/Scences/Game/GuessedRightWordVC.swift
  FindDict/FindDict/Sources/Scences/Game/HintModalVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoReselectModalVC.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorButton.swift
  FindDict/FindDict/Sources/Scences/Game/PhotoSelectorVC.swift
  FindDict/FindDict/Sources/Scences/Tutorial/GameTutorialCVC.swift
Labels: 📱 UI

#86 [Feat] 이미지 크기에 맞게 scaling
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict/Global/Extensions/UIImage+.swift
  FindDict/FindDict/Sources/Scences/Dictionary/DictionaryDetailVC.swift
Labels: 📱 UI

#93 [FEAT] 효과음 추가
  FindDict/FindDict.xcodeproj/project.pbxproj
  FindDict/FindDict/Resources/Sound/CorrectAnswer.wav
  FindDict/FindDict/Resources/Sound/GameClear.wav
  FindDict/FindDict/Resources/Sound/WrongAnswer.wav
  FindDict/FindDict/Sources/Scences/Game/GameResultModal/GameResultSuccessVC.swift
  FindDict/FindDict/Sources/Scences/Game/GameVC.swift
Labels: logic

#95 [Chore] 튜토리얼 사진,문구 수정
  FindDict/FindDict.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindDict/FindDict/Resources/Assets.xcassets/Dictionary.imageset/Dictionary.png
  FindDict/FindDict/Resources/Assets.xcassets/DictionaryDetail.imageset/DictionaryDetail.png
  FindDict/FindDict/Resources/Assets.xcassets/FoundAnswer.imageset/FoundAnswer.png
  FindDict/FindDict/Resources/Assets.xcassets/Game.imageset/Game.png
  FindDict/FindDict/Resources/Assets.xcassets/GameSuccess.imageset/Contents.json
  FindDict/FindDict/Resources/Assets.xcassets/GameSuccess.imageset/GameSuccess.png
  FindDict/FindDict/Resources/Assets.xcassets/Hint.imageset/Hint.png
  FindDict/FindDict/Sources/Scences/Tutorial/GameTutorialCVCModel.swift
Labels: duplicate
